/**
 * Generates the SQL to add or rotate an Admin Portal account.
 *
 *   SEED_EMAIL="you@example.com" SEED_PASSWORD="…" npx tsx scripts/seed-admin.ts
 *   npx wrangler d1 execute kosua-ne-meko-rsvps --remote --file seed-admin.sql
 *
 * Credentials are read from the environment rather than argv so the password
 * never lands in shell history, and only the derived hash is written to disk.
 * Never write a plain-text password into admin_users.
 */
import { writeFileSync } from 'node:fs';
import { hashPassword } from '../functions/_shared/password';

const email = (process.env.SEED_EMAIL ?? '').trim().toLowerCase();
const password = process.env.SEED_PASSWORD ?? '';
const name = process.env.SEED_NAME ?? 'Super Admin';
const role = process.env.SEED_ROLE ?? 'Super Admin';
const out = process.env.SEED_OUT ?? 'seed-admin.sql';

if (!email || !password) {
  console.error('SEED_EMAIL and SEED_PASSWORD are required.');
  process.exit(1);
}
if (password.length < 8) {
  console.error('Refusing to seed: password must be at least 8 characters.');
  process.exit(1);
}

/** Doubles single quotes — the only escaping SQLite string literals need. */
const esc = (value: string): string => value.replace(/'/g, "''");

hashPassword(password).then((hash) => {
  writeFileSync(
    out,
    `-- Generated by scripts/seed-admin.ts. Contains a PBKDF2 hash, not a password.\n` +
      `INSERT INTO admin_users (email, name, password_hash, role)\n` +
      `VALUES ('${esc(email)}', '${esc(name)}', '${esc(hash)}', '${esc(role)}')\n` +
      `ON CONFLICT(email) DO UPDATE SET\n` +
      `  password_hash = excluded.password_hash,\n` +
      `  name          = excluded.name,\n` +
      `  role          = excluded.role;\n`,
  );
  console.log(`Wrote ${out} for ${email}. Apply it with:`);
  console.log(`  npx wrangler d1 execute kosua-ne-meko-rsvps --remote --file ${out}`);
  console.log('Delete the file afterwards.');
});
